import type { Metadata } from "next";
import { inter } from "./fonts";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import StarsBackground from "@/components/StarsBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>
          <StarsBackground>{children}</StarsBackground>
        </body>
      </SessionProvider>
    </html>
  );
}
